/**
 * Pure renderer: `render(state) -> DesiredTree`.
 *
 * Maps the in-memory {@link ModelState} to the full set of desired files (a map of
 * relative POSIX path -> file content). It performs **no I/O** — the writer diffs this
 * desired tree against disk and applies the minimal changes.
 *
 * Layout (see docs/local-sync.md), slice-first:
 *
 *   workspace.json
 *   chapters/[Context]/[chapterId]_[Chapter]/
 *     chapter.json, index.md
 *     slices/[index]_[sliceId]_[Slice]/
 *       slice.json, details.md, comments/[createdAt]_[id]/{comment.json, comment.md}
 *       lanes/[laneType]/[laneId]_[Lane]/
 *         lane.json
 *         elements/[index]_[elementId]_[Element]/
 *           element.json, description.md, details.md,
 *           comments/[createdAt]_[id]/{comment.json, comment.md}
 *   element-details/[Context]/[ElementType]/[Element]/details.md
 *   lane-details/[LaneType]/[Lane]/details.md
 *   milestones/[milestoneId]_[Milestone]/{milestone.json, description.md}
 *
 * All name/label path segments are sanitized; raw values live in the `.json`.
 */

import {
  type ModelState,
  type ChapterState,
  type SliceState,
  type LaneState,
  type ElementState,
  type MilestoneState,
  type ScenarioState,
  type HtmlSnippetState,
  type Comment,
  parseElementDetailsKey,
  parseLaneDetailsKey,
  slicesOfChapter,
  lanesOfChapter,
  elementsInCell,
} from "./model.js";
import { sanitizeSegment, nameSlug, orderedSegment } from "./sanitize.js";

/** A desired file tree: relative POSIX path -> UTF-8 content. */
export type DesiredTree = Map<string, string>;

const GENERATED_MARKER =
  "<!-- Generated by spec-stream (local model sync). Edits here are NOT synced back to prooph board. -->\n";

/** Render the whole model to a desired file tree. */
export function render(state: ModelState): DesiredTree {
  const tree: DesiredTree = new Map();

  tree.set(
    "workspace.json",
    json({
      id: state.workspaceId,
      name: state.workspaceName,
    }),
  );

  for (const chapter of state.chapters.values()) {
    renderChapter(tree, state, chapter);
  }
  renderSharedElementDetails(tree, state);
  renderSharedLaneDetails(tree, state);
  for (const milestone of state.milestones.values()) {
    renderMilestone(tree, milestone);
  }

  // Render workspace-level HTML snippets.
  for (const snippet of state.htmlSnippets.values()) {
    renderHtmlSnippet(tree, snippet);
  }

  // Build the flat UUID → path index so agents can resolve an id to a directory without
  // recursing the whole tree (path is the directory containing the primary .json).
  renderUuidIndex(tree, state);

  return tree;
}

// ─────────────────────── path builders ───────────────────────

function chapterDir(chapter: ChapterState): string {
  const ctx = sanitizeSegment(chapter.context, "no-context");
  return `chapters/${ctx}/${nameSlug(chapter.id, chapter.name)}`;
}
function sliceDir(chapter: ChapterState, slice: SliceState): string {
  return `${chapterDir(chapter)}/slices/${orderedSegment(slice.index, slice.id, slice.label)}`;
}
function laneDirUnderSlice(
  chapter: ChapterState,
  slice: SliceState,
  lane: LaneState,
): string {
  const laneType = sanitizeSegment(lane.type, "lane");
  return `${sliceDir(chapter, slice)}/lanes/${laneType}/${nameSlug(lane.id, lane.label)}`;
}
function elementDir(
  chapter: ChapterState,
  slice: SliceState,
  lane: LaneState,
  el: ElementState,
): string {
  return `${laneDirUnderSlice(chapter, slice, lane)}/elements/${orderedSegment(el.index, el.id, el.name)}`;
}

// ─────────────────────── chapter ───────────────────────

function renderChapter(tree: DesiredTree, state: ModelState, chapter: ChapterState): void {
  const dir = chapterDir(chapter);
  tree.set(
    `${dir}/chapter.json`,
    json({
      id: chapter.id,
      name: chapter.name,
      context: chapter.context,
      index: chapter.index,
      mode: chapter.mode,
      sliceOrder: chapter.sliceOrder,
      laneOrder: chapter.laneOrder,
    }),
  );
  tree.set(`${dir}/index.md`, renderChapterIndex(state, chapter));

  const slices = slicesOfChapter(state, chapter.id);
  const lanes = lanesOfChapter(state, chapter.id);
  for (const slice of slices) {
    renderSlice(tree, state, chapter, slice, lanes);
  }

  // Render scenarios for this chapter.
  for (const scenario of state.scenarios.values()) {
    if (scenario.chapterId === chapter.id) {
      renderScenario(tree, chapter, scenario);
    }
  }
}

function renderChapterIndex(state: ModelState, chapter: ChapterState): string {
  const lines: string[] = [GENERATED_MARKER, `# ${chapter.name}`, ""];
  lines.push(`- **Context:** ${chapter.context}`, `- **Mode:** ${chapter.mode}`, "");
  lines.push("## Slices", "");
  const slices = slicesOfChapter(state, chapter.id);
  if (slices.length === 0) {
    lines.push("_No slices._");
  } else {
    for (const slice of slices) {
      const status = slice.status ? ` — \`${slice.status}\`` : "";
      lines.push(`${slice.index + 1}. **${slice.label}**${status}`);
    }
  }
  lines.push("");
  return lines.join("\n");
}

// ─────────────────────── slice ───────────────────────

function renderSlice(
  tree: DesiredTree,
  state: ModelState,
  chapter: ChapterState,
  slice: SliceState,
  lanes: LaneState[],
): void {
  const dir = sliceDir(chapter, slice);
  tree.set(
    `${dir}/slice.json`,
    json({
      id: slice.id,
      label: slice.label,
      index: slice.index,
      status: slice.status,
      width: slice.width,
      icon: slice.icon,
      milestoneId: slice.milestoneId,
      milestoneName: slice.milestoneName,
      assignee: slice.assignee,
      estimate: slice.estimate,
      timeSpent: slice.timeSpent,
    }),
  );
  tree.set(`${dir}/details.md`, markdown(slice.details));
  renderComments(tree, `${dir}/comments`, slice.comments);

  // Lanes are rendered per slice (slice-first); only lanes that have elements in this
  // slice are materialized, to avoid empty lane dirs under every slice.
  for (const lane of lanes) {
    const cell = elementsInCell(state, lane.id, slice.id);
    if (cell.length === 0) continue;
    renderLane(tree, chapter, slice, lane, cell);
  }
}

// ─────────────────────── lane (per slice) ───────────────────────

function renderLane(
  tree: DesiredTree,
  chapter: ChapterState,
  slice: SliceState,
  lane: LaneState,
  cell: ElementState[],
): void {
  const dir = laneDirUnderSlice(chapter, slice, lane);
  tree.set(
    `${dir}/lane.json`,
    json({
      id: lane.id,
      label: lane.label,
      type: lane.type,
      index: lane.index,
      height: lane.height,
      icon: lane.icon,
    }),
  );
  for (const el of cell) {
    renderElement(tree, chapter, slice, lane, el);
  }
}

// ─────────────────────── element ───────────────────────

function renderElement(
  tree: DesiredTree,
  chapter: ChapterState,
  slice: SliceState,
  lane: LaneState,
  el: ElementState,
): void {
  const dir = elementDir(chapter, slice, lane, el);
  const detailsRef = elementDetailsRef(el);
  tree.set(
    `${dir}/element.json`,
    json({
      id: el.id,
      type: el.type,
      name: el.name,
      context: el.context,
      laneId: el.laneId,
      sliceId: el.sliceId,
      index: el.index,
      icon: el.icon,
      noArrowSource: el.noArrowSource,
      noArrowTarget: el.noArrowTarget,
      detailsRef,
      playFunctionRef: el.playFunction !== undefined ? `${dir}/play-function.ts` : undefined,
      playTypeRef: el.playType !== undefined ? `${dir}/play-type.ts` : undefined,
    }),
  );
  tree.set(`${dir}/description.md`, markdown(el.description));
  tree.set(`${dir}/details.md`, markdown(el.details));
  if (el.playFunction !== undefined) {
    tree.set(`${dir}/play-function.ts`, el.playFunction);
  }
  if (el.playType !== undefined) {
    tree.set(`${dir}/play-type.ts`, `type Payload = ${el.playType}`);
  }
  renderComments(tree, `${dir}/comments`, el.comments);
}

function elementDetailsRef(el: ElementState): string {
  const ctx = sanitizeSegment(el.context, "no-context");
  const type = sanitizeSegment(el.type, "element");
  const name = sanitizeSegment(el.name, el.id);
  return `element-details/${ctx}/${type}/${name}/details.md`;
}

// ─────────────────────── comments ───────────────────────

function renderComments(tree: DesiredTree, baseDir: string, comments: Comment[]): void {
  for (const c of comments) {
    const seg = `${sanitizeSegment(c.createdAt ?? "", c.id)}_${nameSlug(c.id, "")}`;
    const dir = `${baseDir}/${seg}`;
    tree.set(
      `${dir}/comment.json`,
      json({ id: c.id, author: c.author, userId: c.userId, createdAt: c.createdAt }),
    );
    tree.set(`${dir}/comment.md`, markdown(c.text));
  }
}

// ─────────────────────── scenario ───────────────────────

function renderScenario(
  tree: DesiredTree,
  chapter: ChapterState,
  sc: ScenarioState,
): void {
  const dir = `${chapterDir(chapter)}/scenarios/${nameSlug(sc.id, sc.name)}`;
  tree.set(
    `${dir}/scenario.json`,
    json({
      id: sc.id,
      chapterId: sc.chapterId,
      name: sc.name,
      clock: sc.clock,
      initialState: Object.keys(sc.initialState).length > 0 ? sc.initialState : undefined,
      seededEvents: sc.seededEvents.length > 0 ? sc.seededEvents : undefined,
      interactions: sc.interactions.length > 0 ? sc.interactions : undefined,
      expectations: sc.expectations.length > 0 ? sc.expectations : undefined,
      createdAt: sc.createdAt,
      updatedAt: sc.updatedAt,
    }),
  );
}

// ─────────────────────── shared details ───────────────────────

function renderSharedElementDetails(tree: DesiredTree, state: ModelState): void {
  for (const entry of state.sharedElementDetails.values()) {
    if (entry.members.size === 0) continue;
    const { context, type, name } = parseElementDetailsKey(entry.key);
    const ctx = sanitizeSegment(context, "no-context");
    const t = sanitizeSegment(type, "element");
    const n = sanitizeSegment(name, "unnamed");
    tree.set(`element-details/${ctx}/${t}/${n}/details.md`, markdown(entry.body));
  }
}

function renderSharedLaneDetails(tree: DesiredTree, state: ModelState): void {
  for (const entry of state.sharedLaneDetails.values()) {
    if (entry.members.size === 0 || entry.body.length === 0) continue;
    const { type, name } = parseLaneDetailsKey(entry.key);
    const t = sanitizeSegment(type, "lane");
    const n = sanitizeSegment(name, "unnamed");
    tree.set(`lane-details/${t}/${n}/details.md`, markdown(entry.body));
  }
}

// ─────────────────────── milestone ───────────────────────

function renderMilestone(tree: DesiredTree, m: MilestoneState): void {
  const dir = `milestones/${nameSlug(m.id, m.name)}`;
  tree.set(
    `${dir}/milestone.json`,
    json({
      id: m.id,
      name: m.name,
      deadline: m.deadline,
      color: m.color,
      isCompleted: m.isCompleted,
      completedAt: m.completedAt,
      createdAt: m.createdAt,
      updatedAt: m.updatedAt,
      slices: m.slices,
    }),
  );
  tree.set(`${dir}/description.md`, markdown(m.description));
}

// ─────────────────────── html snippets ───────────────────────

/**
 * Render a workspace-level HTML snippet.
 * Stored as `html-snippets/[slug].html` — the raw HTML content is the file body.
 * A companion `[slug].json` carries the slug, name, and timestamps for metadata access.
 */
function renderHtmlSnippet(tree: DesiredTree, snippet: HtmlSnippetState): void {
  const safeSlug = sanitizeSegment(snippet.slug, "snippet");
  tree.set(`html-snippets/${safeSlug}.html`, snippet.snippet);
  tree.set(
    `html-snippets/${safeSlug}.json`,
    json({
      slug: snippet.slug,
      name: snippet.name,
      createdAt: snippet.createdAt,
      updatedAt: snippet.updatedAt,
    }),
  );
}

// ─────────────────────── uuid index ───────────────────────

/**
 * Build `uuid-index.json`: a flat map of `{ [uuid]: "relative/dir/path" }` covering
 * every entity whose primary json lives in a named directory (chapters, slices, lanes,
 * elements, milestones, scenarios). Agents can resolve a UUID received from a changelog
 * event or MCP call to a local path in O(1) without recursing the tree.
 */
function renderUuidIndex(tree: DesiredTree, state: ModelState): void {
  const index: Record<string, string> = {};

  for (const chapter of state.chapters.values()) {
    const cDir = chapterDir(chapter);
    index[chapter.id] = cDir;

    const slices = slicesOfChapter(state, chapter.id);
    const lanes = lanesOfChapter(state, chapter.id);

    for (const slice of slices) {
      const sDir = sliceDir(chapter, slice);
      index[slice.id] = sDir;

      for (const lane of lanes) {
        const cell = elementsInCell(state, lane.id, slice.id);
        if (cell.length === 0) continue;
        const lDir = laneDirUnderSlice(chapter, slice, lane);
        // Lane id may appear multiple times (once per slice); last write wins but all
        // point to a valid directory — agents typically only need one path per lane.
        index[lane.id] = lDir;
        for (const el of cell) {
          index[el.id] = elementDir(chapter, slice, lane, el);
        }
      }
    }

    for (const scenario of state.scenarios.values()) {
      if (scenario.chapterId === chapter.id) {
        index[scenario.id] = `${cDir}/scenarios/${nameSlug(scenario.id, scenario.name)}`;
      }
    }
  }

  for (const milestone of state.milestones.values()) {
    index[milestone.id] = `milestones/${nameSlug(milestone.id, milestone.name)}`;
  }

  // Stable output: sort by uuid so diffs are deterministic.
  const sorted: Record<string, string> = {};
  for (const key of Object.keys(index).sort()) {
    sorted[key] = index[key];
  }
  tree.set("uuid-index.json", JSON.stringify(sorted, null, 2) + "\n");
}

// ─────────────────────── content helpers ───────────────────────

/** Stable, pretty JSON with a trailing newline. `undefined` fields are dropped. */
function json(value: Record<string, unknown>): string {
  const clean: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(value)) {
    if (v !== undefined) clean[k] = v;
  }
  return JSON.stringify(clean, null, 2) + "\n";
}

/** Markdown file body with the generated marker; empty content still writes the marker. */
function markdown(body: string): string {
  const text = typeof body === "string" ? body : "";
  return text.length > 0 ? `${GENERATED_MARKER}\n${text}\n` : GENERATED_MARKER;
}
