import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdirSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { buildOperations } from "./operationBuilder.js";
import type { FileChange } from "./gitDiff.js";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function makeRoot(): string {
  const dir = join(tmpdir(), `spec-stream-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

function writeJson(root: string, relPath: string, data: unknown): void {
  const abs = join(root, relPath);
  mkdirSync(require_dirname(abs), { recursive: true });
  writeFileSync(abs, JSON.stringify(data, null, 2), "utf8");
}

function writeFile(root: string, relPath: string, content: string): void {
  const abs = join(root, relPath);
  mkdirSync(require_dirname(abs), { recursive: true });
  writeFileSync(abs, content, "utf8");
}

function require_dirname(filePath: string): string {
  return filePath.slice(0, filePath.lastIndexOf("/") === -1 ? filePath.lastIndexOf("\\") : filePath.lastIndexOf("/"));
}

// Generated marker that render.ts puts in markdown files.
const MARKER = "<!-- Generated by spec-stream (local model sync). Edits here are NOT synced back to prooph board. -->\n";

// ─── Test fixtures ────────────────────────────────────────────────────────────

const CHAPTER_ID = "chapter-uuid-1";
const SLICE_ID = "slice-uuid-1";
const LANE_ID = "lane-uuid-1";
const ELEMENT_ID = "element-uuid-1";
const MILESTONE_ID = "milestone-uuid-1";

const CHAPTER_DIR = "chapters/App/My-Chapter";
const SLICE_DIR = `${CHAPTER_DIR}/slices/0001_My-Slice`;
const LANE_DIR = `${SLICE_DIR}/lanes/information-flow/My-Lane`;
const ELEMENT_DIR = `${LANE_DIR}/elements/0001_My-Element`;
const MILESTONE_DIR = "milestones/My-Milestone";

function setupChapter(root: string): void {
  writeJson(root, `${CHAPTER_DIR}/chapter.json`, {
    id: CHAPTER_ID,
    name: "My Chapter",
    context: "App",
    mode: "event-modeling",
    index: 0,
  });
}

function setupSlice(root: string): void {
  setupChapter(root);
  writeJson(root, `${SLICE_DIR}/slice.json`, {
    id: SLICE_ID,
    label: "My Slice",
    index: 0,
    status: "draft",
  });
  writeFile(root, `${SLICE_DIR}/details.md`, `${MARKER}\nSome slice details`);
}

function setupLane(root: string): void {
  setupSlice(root);
  writeJson(root, `${LANE_DIR}/lane.json`, {
    id: LANE_ID,
    label: "My Lane",
    type: "information-flow",
    index: 0,
    height: 150,
  });
}

function setupElement(root: string): void {
  setupLane(root);
  writeJson(root, `${ELEMENT_DIR}/element.json`, {
    id: ELEMENT_ID,
    type: "command",
    name: "My Element",
    context: "App",
    laneId: LANE_ID,
    sliceId: SLICE_ID,
    index: 0,
  });
  writeFile(root, `${ELEMENT_DIR}/description.md`, `${MARKER}\nDo something`);
  writeFile(root, `${ELEMENT_DIR}/details.md`, `${MARKER}\nDetailed notes`);
}

function setupMilestone(root: string): void {
  writeJson(root, `${MILESTONE_DIR}/milestone.json`, {
    id: MILESTONE_ID,
    name: "My Milestone",
    deadline: "2026-12-31",
    color: "#3b82f6",
  });
  writeFile(root, `${MILESTONE_DIR}/description.md`, `${MARKER}\nMilestone description`);
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("buildOperations", () => {
  let root: string;

  beforeEach(() => {
    root = makeRoot();
  });

  afterEach(() => {
    rmSync(root, { recursive: true, force: true });
  });

  // ─── Element description update ────────────────────────────────────────────
  it("maps modified description.md to element.update-description", async () => {
    setupElement(root);
    const changes: FileChange[] = [
      { status: "M", path: `${ELEMENT_DIR}/description.md` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    expect(ops).toHaveLength(1);
    expect(ops[0]).toMatchObject({
      kind: "element.update-description",
      chapterId: CHAPTER_ID,
      elementId: ELEMENT_ID,
      newDescription: "Do something",
    });
  });

  // ─── Element details update ────────────────────────────────────────────────
  it("maps modified details.md to element.update-details", async () => {
    setupElement(root);
    const changes: FileChange[] = [
      { status: "M", path: `${ELEMENT_DIR}/details.md` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    expect(ops).toHaveLength(1);
    expect(ops[0]).toMatchObject({
      kind: "element.update-details",
      chapterId: CHAPTER_ID,
      elementId: ELEMENT_ID,
      newDetails: "Detailed notes",
    });
  });

  // ─── Slice details update ──────────────────────────────────────────────────
  it("maps modified slice details.md to slice.update-details", async () => {
    setupSlice(root);
    const changes: FileChange[] = [
      { status: "M", path: `${SLICE_DIR}/details.md` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    expect(ops).toHaveLength(1);
    expect(ops[0]).toMatchObject({
      kind: "slice.update-details",
      chapterId: CHAPTER_ID,
      sliceId: SLICE_ID,
      newDetails: "Some slice details",
    });
  });

  // ─── Element create ────────────────────────────────────────────────────────
  it("maps added element.json to element.create", async () => {
    setupElement(root);
    const changes: FileChange[] = [
      { status: "A", path: `${ELEMENT_DIR}/element.json` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    expect(ops).toHaveLength(1);
    expect(ops[0]).toMatchObject({
      kind: "element.create",
      chapterId: CHAPTER_ID,
      name: "My Element",
      type: "command",
      laneId: LANE_ID,
      sliceId: SLICE_ID,
    });
  });

  // ─── Element create picks up description and details ──────────────────────
  it("element.create includes description and details from disk", async () => {
    setupElement(root);
    const changes: FileChange[] = [
      { status: "A", path: `${ELEMENT_DIR}/element.json` },
      { status: "A", path: `${ELEMENT_DIR}/description.md` },
      { status: "A", path: `${ELEMENT_DIR}/details.md` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    // Should only be one create (deduplicated), not three operations
    const creates = ops.filter((o) => o.kind === "element.create");
    expect(creates).toHaveLength(1);
    expect(creates[0]).toMatchObject({
      kind: "element.create",
      description: "Do something",
      details: "Detailed notes",
    });
  });

  // ─── Slice create ──────────────────────────────────────────────────────────
  it("maps added slice.json to slice.create", async () => {
    setupSlice(root);
    const changes: FileChange[] = [
      { status: "A", path: `${SLICE_DIR}/slice.json` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    expect(ops).toHaveLength(1);
    expect(ops[0]).toMatchObject({
      kind: "slice.create",
      chapterId: CHAPTER_ID,
      label: "My Slice",
    });
  });

  // ─── Chapter create ────────────────────────────────────────────────────────
  it("maps added chapter.json to chapter.create", async () => {
    setupChapter(root);
    const changes: FileChange[] = [
      { status: "A", path: `${CHAPTER_DIR}/chapter.json` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    expect(ops).toHaveLength(1);
    expect(ops[0]).toMatchObject({
      kind: "chapter.create",
      name: "My Chapter",
      context: "App",
    });
  });

  // ─── Milestone create ──────────────────────────────────────────────────────
  it("maps added milestone.json to milestone.create", async () => {
    setupMilestone(root);
    const changes: FileChange[] = [
      { status: "A", path: `${MILESTONE_DIR}/milestone.json` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    expect(ops).toHaveLength(1);
    expect(ops[0]).toMatchObject({
      kind: "milestone.create",
      name: "My Milestone",
      deadline: "2026-12-31",
    });
  });

  // ─── Milestone description update ─────────────────────────────────────────
  it("maps modified milestone description.md to milestone.update", async () => {
    setupMilestone(root);
    const changes: FileChange[] = [
      { status: "M", path: `${MILESTONE_DIR}/description.md` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    expect(ops).toHaveLength(1);
    expect(ops[0]).toMatchObject({
      kind: "milestone.update",
      milestoneId: MILESTONE_ID,
      description: "Milestone description",
    });
  });

  // ─── Operation ordering ────────────────────────────────────────────────────
  it("orders creates before updates", async () => {
    setupElement(root);
    const changes: FileChange[] = [
      { status: "M", path: `${ELEMENT_DIR}/description.md` },
      { status: "A", path: `${ELEMENT_DIR}/element.json` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    const kinds = ops.map((o) => o.kind);
    const createIdx = kinds.indexOf("element.create");
    const updateIdx = kinds.indexOf("element.update-description");
    // create must come before update
    expect(createIdx).toBeLessThan(updateIdx);
  });

  it("orders chapter creates before slice creates", async () => {
    setupSlice(root);
    const changes: FileChange[] = [
      { status: "A", path: `${SLICE_DIR}/slice.json` },
      { status: "A", path: `${CHAPTER_DIR}/chapter.json` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    const kinds = ops.map((o) => o.kind);
    expect(kinds.indexOf("chapter.create")).toBeLessThan(kinds.indexOf("slice.create"));
  });

  // ─── Element play-function update ─────────────────────────────────────────
  it("maps modified play-function.ts to element.update-config", async () => {
    setupElement(root);
    writeFile(root, `${ELEMENT_DIR}/play-function.ts`, "async function play() { return {}; }");
    const changes: FileChange[] = [
      { status: "M", path: `${ELEMENT_DIR}/play-function.ts` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    expect(ops).toHaveLength(1);
    expect(ops[0]).toMatchObject({
      kind: "element.update-config",
      chapterId: CHAPTER_ID,
      elementId: ELEMENT_ID,
      playFunction: "async function play() { return {}; }",
    });
  });

  // ─── Generated files are skipped ──────────────────────────────────────────
  it("ignores index.md (generated)", async () => {
    setupChapter(root);
    const changes: FileChange[] = [
      { status: "M", path: `${CHAPTER_DIR}/index.md` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    expect(ops).toHaveLength(0);
  });

  // ─── Non-model paths are ignored ──────────────────────────────────────────
  it("ignores uuid-index.json", async () => {
    const changes: FileChange[] = [{ status: "M", path: "uuid-index.json" }];
    expect(await buildOperations({ syncRootAbs: root, changes })).toHaveLength(0);
  });

  it("ignores workspace.json", async () => {
    const changes: FileChange[] = [{ status: "M", path: "workspace.json" }];
    expect(await buildOperations({ syncRootAbs: root, changes })).toHaveLength(0);
  });

  // ─── Generated marker is stripped from markdown ───────────────────────────
  it("strips the generated marker from markdown content", async () => {
    setupElement(root);
    const changes: FileChange[] = [
      { status: "M", path: `${ELEMENT_DIR}/description.md` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    const op = ops[0] as { newDescription: string };
    // Should not contain the marker
    expect(op.newDescription).not.toContain("Generated by spec-stream");
    expect(op.newDescription).toBe("Do something");
  });

  // ─── Slice status update from slice.json ──────────────────────────────────
  it("emits slice.update-status when slice.json is modified", async () => {
    setupSlice(root);
    // Update slice.json to planned status
    writeJson(root, `${SLICE_DIR}/slice.json`, {
      id: SLICE_ID,
      label: "My Slice",
      index: 0,
      status: "planned",
    });
    const changes: FileChange[] = [
      { status: "M", path: `${SLICE_DIR}/slice.json` },
    ];
    const ops = await buildOperations({ syncRootAbs: root, changes });
    const statusOp = ops.find((o) => o.kind === "slice.update-status");
    expect(statusOp).toMatchObject({
      kind: "slice.update-status",
      sliceId: SLICE_ID,
      newStatus: "planned",
    });
  });
});
